name: flutter_pocketbase_tutorial
description: "Flutter Pocketbase Tutorial"
publish_to: 'none' 
version: 1.1.0+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pocketbase: ^0.18.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
